
title: Crabbie & Co
tagline: Edinburgh's hottest home renovation, refurbishment and restoration business

description: |


url: https://crabbieco.github.io

logo: https://crabbieco.github.io/assets/favicon.png

social:
  name: Stockbridge Decorators
  links:
    - https://www.instagram.com/crabbieandco/
    - https://g.page/

locale: en_UK

theme: minima
show_excerpts: true

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
